### PR TITLE
Move GitAuth to EE

### PR DESCRIPTION
**Pull request by AlinaGoaga**
Part of https://app.zenhub.com/workspaces/team-pesto-6127680175876a0014fc5657/issues/weaveworks/weave-gitops-enterprise/1879

**What changed?**
We need to make some changes to Git Auth - specifically let the user choose the url repo. This targets components present here so we're taking this opportunity to move Git Auth to EE since it's not used here. 
- remove applications related content from AppContext 
- remove Git Auth components and context from ui 
- updated exports for EE
- removed applications from api

### CODE REVIEW

**Comment by AlinaGoaga** [comment]
@weaveworks/weavegitops-core-maintainers Hey team! When you have a minute can you have a look at this PR please see if I've missed anything? We've already added the relevant api endpoint and components to EE and merged to main. Thanks Also tagging Simon @foot

**Review by opudrovs — APPROVED** [review]
Tested the UI, LGTM! 🎉

**Comment by AlinaGoaga** [comment]
@weaveworks/weavegitops-core-maintainers  Hello team, sorry this fell off my radar. Coming back to it now. Thank you for the UI approval Olga, can someone have a look at the BE files also please? Thanks!

**Comment by opudrovs** [comment]
@AlinaGoaga the backend looks fine to me! Tested the app locally, everything is working as expected. 🎉 

Your PR can be merged as is, but I will create a PR with Snyk security fixes in a couple hours, when I am back. So, we can merge it after that one is merged to be on the safe side.

**Pull request merged**
