### PR TITLE
Fix for image-spec vuln

### PR DESCRIPTION
**Pull request by jpellizzari**
Fixes a vulnerability in `image-spec`: https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMOPENCONTAINERSIMAGESPECSPECSGOV1-1922832

### CODE REVIEW

**Comment by rokshana-b** [comment]
@jpellizzari Why is one of the scan results missing?

image

**Comment by jpellizzari** [comment]
> @jpellizzari Why is one of the scan results missing?
> 

No idea

**Comment by rokshana-b** [comment]
@jpellizzari I'm approving this PR since everything else seems ok. The branch seems `"merge-able"` & the missing check seems neutral ¯_(ツ)_/¯

**Review by rokshana-b — APPROVED** [review]

**Comment by rokshana-b** [comment]
Other Branches:

image

This Branch:

image

**Comment by jpellizzari** [comment]
> Other Branches:
> 
> image
> 
> This Branch:
> 
> image

You have highlighted two different jobs in these screenshots

**Pull request merged**
