### PR TITLE
Add edit icon, modify Pipelines and Delivery icons for EE dark mode

### PR DESCRIPTION
**Pull request by joshri**
Adding edit icon so EE can supply non-Mui specific colors for dark mode. Adjust Pipelines and Delivery icons for EE dark mode

before:
image

after:
image

Unfortunately the Pipelines icon is in a tough spot - the fill on the middle section can not be hardcoded to white, but once it's transparent we get that extra filled-in section on the wings. Needs an adjustment in Figma.

Dark Mode Edit button:
image

### CODE REVIEW

**Comment by TheGostKasper** [comment]
I believe we need to keep it as it's, there's a huge difference in Icons as 
image
image

but there's a chance to enhance the `PolicyMode` to mock the old styles `color fill or size` .

@AsmaaNabilBakr

**Comment by joshri** [comment]
Cool - made an issue here - we can't have the same icon twice so the svg will need to support both styles https://github.com/weaveworks/weave-gitops/issues/3782

**Comment by opudrovs** [comment]
Some tests are failing. The order of imports.

**Comment by joshri** [comment]
oop thanks Olga - fixed.

**Review by opudrovs — APPROVED** [review]

**Pull request merged**
