### PR TITLE
remove tenancy cmd from core

### PR DESCRIPTION
**Pull request by alichaddad**
**What changed?**
Removed tenancy commands from core

**Why was this change made?**
Tenancy command should work as an additional plugin to the gitops binary

### CODE REVIEW

**Review by jmickey — APPROVED** [review]

**Review by sarataha — APPROVED** [review]
LGTM! 👍

**Comment by chanwit** [comment]
Thank you @alichaddad!
Some entries in `go.sum` needs to be refreshed because of the code removal.
Could you please re-run `go mod tidy` and re-push again?

**Comment by alichaddad** [comment]
Thanks @chanwit , it should be ok now

**Comment by chanwit** [comment]
Ouch @alichaddad. It seems this PR requires another rebase.

**Pull request merged**
