### PR TITLE
Versioning updates to documentation website    

### PR DESCRIPTION
**Pull request by Himangini**
Closes https://github.com/weaveworks/weave-gitops/issues/3556

**What changed?**
- [x]  Remove this [Introduction](https://docs.gitops.weave.works/docs/next/enterprise/intro/index.html) page. 
- [x]  Remove this [Architecture](https://docs.gitops.weave.works/docs/next/architecture) page.
- [x]  Remove this [Upgrading](https://docs.gitops.weave.works/docs/next/enterprise/upgrading) page.
- [x]  Remove this [Troubleshooting](https://docs.gitops.weave.works/docs/next/troubleshooting/index.html) page. 
- [x]  Remove this [Examples](https://docs.gitops.weave.works/docs/next/examples/sock-shop/index.html) page.
- [x] Old docs versions are sidelined off from the latest doc version, stored in their own section.
- [x] Old docs versions retain the same styling as the user docs.
- [x] The component tagging at the top right is gone.
- [x] Deleted versions from `versioned_docs` only kept versions from `0.16.0` and above

**Why was this change made?**
See the discussion on the ticket

**How was this change implemented?**

**How did you validate the change?**
Local Testing
Screenshot 2023-07-06 at 13 45 02
Screenshot 2023-07-06 at 13 45 20

**Release notes**
Versioning updates to the documentation website    

**Documentation Changes**

### CODE REVIEW

**Comment by yiannistri** [comment]
@Himangini any chance you could break up this PR into smaller ones? For example, 1 PR per version removed? It's quite difficult to review a PR with 1807 files changed.

**Comment by Himangini** [comment]
> @Himangini any chance you could break up this PR into smaller ones? For example, 1 PR per version removed? It's quite difficult to review a PR with 1807 files changed.

@yiannistri How about I separate out deleted folders in one/two PRs? There's not much to review for them.

**Review by yiannistri — APPROVED** [review]

**Comment by yiannistri** [comment]
I've had to use the sidebar/filter to hide deleted items and understand what was being deleted.

**Comment by LappleApple** [comment]
@Himangini Major thanks for this big step forward

**Pull request merged**
