### PR TITLE
Update all Flux (related) dependencies

### PR DESCRIPTION
**Pull request by hiddeco**
**What changed?**

- Update all Flux dependencies to `v0.29.x`
- Move to v1beta2 Flux Source API
- Update source.toolkit.fluxcd.io versions in docs
- Update Flux Source API test CRDs
- (Properly) update Helm to v3.8.2
- Update golang.org/x/{crypto,oauth2}

**Why was this change made?**

To stay up-to-date with latest Flux, and mitigate https://github.com/advisories/GHSA-8c26-wmh5-6g9v.

**How was this change implemented?**
 
Go Modules update, and relevant changes to Go imports (including a change of imports from `github.com/fluxcd/source-controller/api/v1beta1` to `/v1beta2`) and other Source API related files.

:rotating_light: **NB:** the simplicity of this change means the application is no longer able to see Source resources without the `v1beta2` Source API CRD being present on the cluster.

**How did you validate the change?**

:warning: Tests seem to pass, but still requires (human/manual) validation.

**Release notes**

This updates to the Flux Source v1beta2 API, and requires Flux `>=v0.28.0` (or at least source-controller `>=0.22.0` including Source API `v1beta2` CRDs) to be installed on the cluster. The [upgrade instructions for Flux v0.28.0 apply post-upgrade](https://github.com/fluxcd/flux2/discussions/2567).

**Documentation Changes**

Updated `source.toolkit.fluxcd.io/v1beta1` examples to `source.toolkit.fluxcd.io/v1beta2`.

### CODE REVIEW

**Comment by hiddeco** [comment]
All remaining test failures seem related to missing secrets because my branch originates from a fork.

**Review by jpellizzari — APPROVED** [review]
LGTM. I think this is low-risk enough to merge and check it out on our fancy new staging clusters.

**Comment by ozamosi** [comment]
Did very basic manual tests:
* When the flux schema and expected gitops schema aren't matching, gitops crashes and won't turn on. Opened #2030 to fix that.
* After applying #2030, if you run this code with an old flux, you get an error on the source page: `failed to list resources: [cluster="Default" err="no matches for kind "HelmRepository" in version "source.toolkit.fluxcd.io/v1beta2""]`. It's an error, improving it is out of scope for this PR. 
* Other pages still seem to work (though e.g. graphs won't contain sources).

**Review by yitsushi — APPROVED** [review]
It looked scarier (based on that `+1,818 −566`) than it is actually.

**Review by ozamosi — APPROVED** [review]

**Pull request merged**
