### PR TITLE
Convert to yarn for package management

### LINKED ISSUE #3943: Convert to `yarn` for package management
We had originally built the Flux dashboard with npm to avoid another tool/ecosystem when it was under the fluxcd umbrella. That carried over to WeGO core.

We should convert to yarn for consistency with EE.

AC:
* Deps managed by Yarn
* We need all CI and Makefile references to `npm` to be changed to `yarn`.

### PR DESCRIPTION
**Pull request by jpellizzari**
Closes #3943

Moves Core to use the same package manager as EE. This is really only to enforce consistency; we chose `yarn` as it a bit faster (historically) and has a nicer UX.

**Note**: Some scripts that run during releases may still be `npm` to reduce the risk of finding issues during a release.

### CODE REVIEW

**Review by joshri — COMMENTED** [review]
Did upgrading eslint cause all those typescript errors?

**Comment by foot** [comment]
Yeah it looks like the yarn.lock is using the react v18 types which seem to introduce these issues https://github.com/bvaughn/react-error-boundary/issues/111#issuecomment-1101850212

If we can bump it back to 17.x in the yarn.lock somehow it will mirror the package-lock and we can maybe revert the code changes.

**Comment by jpellizzari** [comment]
> Did upgrading eslint cause all those typescript errors? If we can get rid of the new `@ts-ignore`s we should

I tried removing most of these, but the `Modal` is being problematic for some reason. Unfortunately, we have some `@types/` that require `@types/react` at `18.X`, so we do have the two different type definitions.

**Comment by jpellizzari** [comment]
Here is a summary of the `@types/react` dep tree:

```
$ yarn why @types/react
yarn why v1.22.19
[1/4] Why do we have the module "@types/react"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@types/react@17.0.64"
info Has been hoisted to "@types/react"
info Reasons this module exists
   - Specified in "devDependencies"
   - Hoisted from "@types#react-dom#@types#react"
info Disk size without dependencies: "184KB"
info Disk size with unique dependencies: "1.39MB"
info Disk size with transitive dependencies: "1.39MB"
info Number of shared dependencies: 3
=> Found "@types/react-router-dom#@types/react@18.2.20"
info This module exists because "@types#react-router-dom" depends on it.
info Disk size without dependencies: "392KB"
info Disk size with unique dependencies: "1.59MB"
info Disk size with transitive dependencies: "1.59MB"
info Number of shared dependencies: 3
=> Found "@types/styled-components#@types/react@18.2.20"
info This module exists because "@types#styled-components" depends on it.
info Disk size without dependencies: "392KB"
info Disk size with unique dependencies: "1.59MB"
info Disk size with transitive dependencies: "1.59MB"
info Number of shared dependencies: 3
=> Found "@testing-library/react-hooks#@types/react@18.2.20"
info Reasons this module exists
   - "@testing-library#react-hooks" depends on it
   - Hoisted from "@testing-library#react-hooks#@types#react-dom#@types#react"
info Disk size without dependencies: "392KB"
info Disk size with unique dependencies: "1.59MB"
info Disk size with transitive dependencies: "1.59MB"
info Number of shared dependencies: 3
=> Found "@types/hoist-non-react-statics#@types/react@18.2.20"
info This module exists because "@types#styled-components#@types#hoist-non-react-statics" depends on it.
info Disk size without dependencies: "392KB"
info Disk size with unique dependencies: "1.59MB"
info Disk size with transitive dependencies: "1.59MB"
info Number of shared dependencies: 3
=> Found "@types/react-router#@types/react@18.2.20"
info This module exists because "@types#react-router-dom#@types#react-router" depends on it.
info Disk size without dependencies: "392KB"
info Disk size with unique dependencies: "1.59MB"
info Disk size with transitive dependencies: "1.59MB"
info Number of shared dependencies: 3
=> Found "@types/react-test-renderer#@types/react@18.2.20"
info This module exists because "@testing-library#react-hooks#@types#react-test-renderer" depends on it.
info Disk size without dependencies: "392KB"
info Disk size with unique dependencies: "1.59MB"
info Disk size with transitive dependencies: "1.59MB"
info Number of shared dependencies: 3
=> Found "@types/react-transition-group#@types/react@18.2.20"
info This module exists because "@material-ui#core#@types#react-transition-group" depends on it.
info Disk size without dependencies: "392KB"
info Disk size with unique dependencies: "1.59MB"
info Disk size with transitive dependencies: "1.59MB"
info Number of shared dependencies: 3
Done in 0.39s.

```

**Review by joshri — APPROVED** [review]

**Comment by foot** [comment]
Yeah.. it looks like we've bumped up to 18 for `react-test-renderer` etc.. in the yarn.lock etc, which may cause issues later as we're still on react 17?

`yarn import` seems to keep `react-test-renderer` back on 17 etc and aligned with the version of react we're using. Could give that go?

**Comment by jpellizzari** [comment]
> yarn import seems to keep react-test-renderer back on 17 etc and aligned with the version of react we're using. Could give that go?

I had no idea about `yarn import` :+1: . Updated.

**Pull request merged**
