### PR TITLE
Using default Fail function so we can see the precise line of the error

### PR DESCRIPTION
**Pull request by josecordaz**
**What changed?**
The registration of the fail handler in testing.

**Why?**
It was not showing the precise location of the error

**How did you test it?**
I added temporary code to make test fail on purpose and validate the error line is correct.

**Release notes**

**Documentation Changes**

### CODE REVIEW

**Comment by josecordaz** [comment]
no more references to assertion.go 
image

**Comment by josecordaz** [comment]
I added a test to check for panics, it worked as well.
image
image

**Review by jpellizzari — APPROVED** [review]
LGTM. @josecordaz is this related to https://github.com/weaveworks/weave-gitops/issues/402?

**Comment by josecordaz** [comment]
> LGTM. @josecordaz is this related to #402?

@jpellizzari unfortunately this is not related. This still continue the execution of the test. I'll try to do some research in how to do that.

**Pull request merged**
