### PR TITLE
Standardize the sync/suspend/edit buttons

### PR DESCRIPTION
**Pull request by opudrovs**
Part of https://github.com/weaveworks/weave-gitops-enterprise/issues/3374

- Replaced the Sync/Suspend/Resume controls, used in the `SyncActions` and `CheckboxActions` components, with the new Sync/Suspend/Resume controls (the `SyncControl` component).

- Moved all components, related to syncing and suspending objects (existing `SyncActions` and `CheckboxActions` and new `SyncControls` and `ResumeIcon`), to the `Sync` folder.

- Updated the related UI snapshot.

- Added `SyncControls` to exports.

- Moved custom actions to the start (left) of `SyncControls` buttons.
 
- Re-arranged icons in `IconType` alphabetically (because it was hard to add new icons – to decide to which part of the list of icons or select cases to add new icon and to check if they already exist in the project, now it's somewhat easier).

Notes:
- I've kept the original logic of creating sync/suspend handlers in general. Only added passing them to the new standartized `SyncControls` component and passing with/without source sync options (set with the new radio buttons) to the handlers.

- We decided not to add Sync/Suspend notifications to enterprise for the time being. Notifications will be covered in the follow-up issues.

Screen recording of the new controls working in OSS:

https://github.com/weaveworks/weave-gitops/assets/8824708/c2e26671-184f-4e3e-82df-16086f593934

Design (there might be some differences between video and Figma design or design system, I tried to combine it in the most logical way):

The latest video with the design:
https://github.com/weaveworks/weave-gitops-enterprise/issues/3374#issuecomment-1745203249
Figma:
https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?type=design&node-id=20086-71968&mode=design&t=46JWHoVfIwzQyShI-0

### CODE REVIEW

**Comment by opudrovs** [comment]
There is an enterprise counterpart to this PR:
https://github.com/weaveworks/weave-gitops-enterprise/pull/3487
But tests in it just started failing after updating the OSS branch in it (probably because of this PR merged https://github.com/weaveworks/weave-gitops/pull/4096 ), so, I hope it will be resolved after the following PR is merged:
https://github.com/weaveworks/weave-gitops-enterprise/pull/3556
But the current PR can be reviewed independently.

**Comment by opudrovs** [comment]
@foot merged a small PR updating enterprise with the latest OSS main, so I will continue working on the enterprise counterpart of the current PR. But the current PR can be reviewed already.

**Comment by opudrovs** [comment]
Add links to the latest video and Figma.

**Comment by opudrovs** [comment]
Changed the format of my screen recording to MP4.

**Review by jpellizzari — APPROVED** [review]
LGTM! Nice work

**Review by joshri — APPROVED** [review]
This is awesome! Great code!

I noticed my sync requests in the ImageAutomations section are timing out, but I don't have enough faith in the objs on my cluster to say for sure if it's because of this PR - were you able to test img repos and update automations?

**Comment by opudrovs** [comment]
@joshri thank for notifying me about the issue!

I don't think it is related to the current PR, because it should not affect the backend. But there was another PR merged in a few days ago which introduced some major changes to the sync/suspend backend code.

I will re-test my PR now with some ImageAutomations objects.

**Comment by joshri** [comment]
Yep - figured as much. I think this is safe to merge and we should address whatever's happening/not happening there in a follow up

**Comment by opudrovs** [comment]
@joshri tested several requests, have not been able to receive request timeout or an error for iamge repos or image update automations, works fine for me.

Screenshot 2023-10-30 at 21 44 09
Screenshot 2023-10-30 at 21 44 17
Screenshot 2023-10-30 at 21 44 23
Screenshot 2023-10-30 at 21 44 37
Screenshot 2023-10-30 at 21 44 50
Screenshot 2023-10-30 at 21 45 03

**Comment by opudrovs** [comment]
I only managed to reproduce request timeout (in most cases, but sometimes the request still succeeds) when trying to sync many objects, some of which are red or stuck in reconciling. But I see this issue in both main and current branches:

Screenshot 2023-10-30 at 22 21 36

Screenshot 2023-10-30 at 22 24 40

**Comment by opudrovs** [comment]
Re-tested the current PR, works fine, so I am merging it. Will merge the enterprise part of this issue when enterprise is updated for the main OSS branch.

If you need to update enterprise with the current changes tomorrow, while there is a public holiday in Germany, you can add the following changes to Terraform object tests:
https://github.com/weaveworks/weave-gitops-enterprise/pull/3487/files#diff-6c94d245e3caa02985486f6d6925631e02882ccd7d7b9f824fb92ae30efde607

**Pull request merged**
