### PR TITLE
Add initial (naive) BitBucket Server support

### PR DESCRIPTION
**Pull request by jpellizzari**
Part of https://github.com/weaveworks/weave-gitops-enterprise/issues/2271

Adds repo URL parsing support for BitBucket using a simple path match.

### CODE REVIEW

**Comment by jpellizzari** [comment]
@yiannistri It wasn't immediately obvious how we can detect a bitbucket provider URL using Viper or env vars. Any ideas there?

**Comment by yiannistri** [comment]
@jpellizzari  we don't need to detect the provider from the URL, there's a map[string]string that gets populated from a Kubernetes secret that maps the URL to the provider type, for example in the `detectGitProviderFromURL` function the `gitHostTypes` parameter will be
```
gitHostTypes[bitbucket.acme.com: bitbucket-server
```
So we can use that value to determine the provider.

**Comment by yiannistri** [comment]
There's a reference to this in the docs but it's not super clear https://github.com/weaveworks/weave-gitops/blob/main/website/docs/installation/weave-gitops-enterprise/index.mdx?plain=1#L233-L236

**Comment by jpellizzari** [comment]
> @jpellizzari we don't need to detect the provider from the URL, there's a map[string]string that gets populated from a Kubernetes secret that maps the URL to the provider type, for example in the `detectGitProviderFromURL` function the `gitHostTypes` parameter will be

Fixed! PTAL

**Review by yiannistri — APPROVED** [review]

**Pull request merged**
