### PR TITLE
Make nav sticky and adjust logo/top bar height

### LINKED ISSUE #1970: Left sidebar should not scroll with detail view
As a user I want the detail view and menu scrolling to be two different actions.  When I scroll the detail view the left side bar should also not scroll at the same time.

### Acceptance Criteria
1. When I go to a page in Weave GitOps with enough content that requires scrolling then when I scroll the leftside menu does not scroll.
2. When I shrink the height of the Weave GitOps application so the left side menu requires scrolling then it should scroll independently from the detail view.
3. When there is not enough content to scroll in either the menu or the detail view then I should not have any scrolling behavior in either area.

Screenshot 2022-04-20 at 16 50 37

### LINKED ISSUE #2218: Make navigation scroll separately
The left navigation and right (main) content should scroll separately. If there is a lot of content on the right side it should scroll where as the left navigation stays fixed.

### LINKED ISSUE #2233: Reduce header size in entire app
As a user I want to see as much content as possible.

### Solution

The header should be 60px

### Acceptance Criteria

1. The header matches the design in the screenshot below.
2. The behavior of the header does not change.  I.e. it should still stick to the top
3. Note that the logo is formatted differently on this version.

### PR DESCRIPTION
**Pull request by joshri**
Closes #1970 
Closes #2233 
Closes #2218 

The nav now has a fixed position - this comes along with fixing the main content so it doesn't always start overflowing the page when it doesn't have to, and a slight adjustment to the logo and top bar height.

### CODE REVIEW

**Comment by opudrovs** [comment]
Something might be wrong with the graph. This is what I see for this branch in both Chrome and Firefox on Mac:

Screenshot 2022-05-31 at 20 21 35

This is what I see for the the main branch:

Screenshot 2022-05-31 at 20 26 55

**Comment by joshri** [comment]
Oof.....looks like the svg isn't taking up 100% like it's told to. Looking into it.

**Comment by joshri** [comment]
> @joshri the logo and top bar look fine to me. Scrolling of the detail view works separately, as expected.
> 
> The only minor issue is that in acceptance criteria in #1970 there is the following:
> 
> ```
> 2. When I shrink the height of the Weave GitOps application so the left side menu requires scrolling then it should scroll independently from the detail view.
> ```
> 
> I haven't managed to make the left side menu scroll in Chrome on a Mac. Attaching the screenshot:
> 
> Screenshot 2022-05-31 at 17 38 45
> 
> Is it expected behavior or will the scrollbar appear in the left side menu if there are more items in the menu?

I'm interpreting that to mean that the nav should have overflow-y: scroll - adding now

**Comment by joshri** [comment]
> Something might be wrong with how the graph is rendered (SVG height?). This is what I see for this branch in both Chrome and Firefox on Mac:

Great catch Olga thank you for spotting that - I believe I have found the culprit - here's a screen of what I'm seeing.

image

**Comment by opudrovs** [comment]
@joshri can confirm that the left menu is scrolling and the graph is visible, but now, if I reduce screen height, the detail view on the right stopped scrolling and the text on it is sort of jumbled together.

Screenshot 2022-06-01 at 10 20 47

**Review by opudrovs — APPROVED** [review]
Tested it locally, LGTM.

**Pull request merged**
