### PR TITLE
Text for app subcommand

### PR DESCRIPTION
**Pull request by D3nn**
**What changed?**
Add descriptive text for the wego app subcommand when running command `wego`

**Why?**
Previously the app subcommand had no description

**How did you test it?**
Ran the command `wego` and verified the app subcommand had descriptive text

**Release notes**

**Documentation Changes**

### CODE REVIEW

**Comment by D3nn** [comment]
PR has been submitted for review

**Comment by jpellizzari** [comment]
@D3nn showing 0 files changed for this one?

**Comment by D3nn** [comment]
> @D3nn showing 0 files changed for this one?

A merge from main in the UI clobbered some changes. Fix

**Review by jpellizzari — APPROVED** [review]
Not super familiar with the `cobra` package, but LGTM!

**Comment by D3nn** [comment]
When I look at the wego-gitops repo with the branch `text_for_app_subcommand` and look at those files, there aren't any conflicts in the files.  And from my local branch of the same name (which I verified is tracking the correct upstream branch), I can do "git pull" and look at those files, I still don't see conflicts in those files.  I guess I'm stuck with editing the files via the GitHub UI...

**Comment by D3nn** [comment]
Deleting this PR and will re-spin the PR with my local version of the branch.

**Pull request closed without merging**
