### PR TITLE
Regenerate proto related objects after renaming ConfigURL to ConfigRepo

### PR DESCRIPTION
**Pull request by josecordaz**
Closes: 

**What changed?**
- It wasn't mapping properly the value of the field `ConfigRepo` when coming from the UI
- Regenerated proto related objects

**Why?**
- Adding an app from the UI using a config repo wasn't working properly. The PR was created in the app repo instead of the config repo.
- Some proto related objects didn't include the recent change in the field `ConfigRepo`

**How did you test it?**
- Manually using UI to make sure it works
- Manually using CI to make sure everything stills works

**Release notes**

**Documentation Changes**

### CODE REVIEW

**Comment by josecordaz** [comment]
> I want this tested and verified from both the CLI and UI.

I tested it that way

**Comment by palemtnrider** [comment]
I see you changed the app CRD, can you verify that the resulting app CR has config_repo populated correctly.

**Comment by palemtnrider** [comment]
Can you also make sure commits and application status work correctly with the new CR in the cluster?

**Comment by josecordaz** [comment]
> Can you also make sure commits and application status work correctly with the new CR in the cluster?

This is working properly, just tested it.

**Comment by josecordaz** [comment]
swagger json files changed because of an update on the libraries related to the swagger generator on my local environment:

```
go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway \
    github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 \
    google.golang.org/protobuf/cmd/protoc-gen-go \
    google.golang.org/grpc/cmd/protoc-gen-go-grpc
```

**Review by palemtnrider — APPROVED** [review]
LGTM

**Pull request merged**
