### PR TITLE
Docs changes in WGE install guide, cluster mgmt pages

### PR DESCRIPTION
**Pull request by LappleApple**
Closes

**What changed?**

Folds a number of pages into the install WGE guide for user discovery. Addresses link changes in current and v0.29.0 versions. Addresses feedback from CX and Engineering related to missing or inaccurate information in some cluster mgmt pages. 

**Why was this change made?**

To fix errors, gaps, and other docs issues

**How was this change implemented?**

Substantial changes triggered by feedback from Sales and other internal parties about issues using the user docs. Gets rid of the current "Access Configuration" section in order to fold pages and content into the installation guide where users are more likely to expect and seek them.

**How did you validate the change?**

Ran npm run build to fix broken links

**Release notes**

Fixes errors and gaps in release guide Cluster Management and WGE Install guide

**Documentation Changes**

The PR is a doc change

### CODE REVIEW

**Comment by LappleApple** [comment]
Fixes https://github.com/weaveworks/weave-gitops/issues/3886

**Comment by enekofb** [comment]
@LappleApple why the PR does not uses the [PR template](https://github.com/weaveworks/weave-gitops/blob/main/.github/pull_request_template.md) ? 

I find it useful in particular for reviewers to frame the change: 

For example, in PR description says 

>Folds a number of pages into the install WGE guide for user discovery. 

But does no provides context on the current issue of user discovery and how this enhances that situation.

**Comment by LappleApple** [comment]
@enekofb Addressed comment

**Review by enekofb — COMMENTED** [review]
It seems that CI docs job [fails](https://github.com/weaveworks/weave-gitops/actions/runs/5783073091/job/15671149652)

Tried to run it locally with the same issue

```bash
➜  website git:(docs-changes-aug7) GA_KEY=fakekey yarn start                                                                                                                                                                                                                                                                                    
[INFO] Starting the development server...
[ERROR] Loading of version failed for version current
[ERROR] Error: Invalid sidebar file at "sidebars.js".


```

**Comment by LappleApple** [comment]
@enekofb I typically do that, and did so before filing this, but we've made changes since then. I'll run again tomorrow.

**Comment by LappleApple** [comment]
Closing in favor of https://github.com/weaveworks/weave-gitops/pull/3955.

**Pull request closed without merging**
