### PR TITLE
Removed duplicate fail register

### PR DESCRIPTION
**Pull request by josecordaz**
Closes:  
- #1164 

**What changed?**
- Removed duplicate ginkgo failure registration

**Why?**
- When tests fail it doesn't show the exact line where the error occurred.

**How did you test it?**
- CI

**Release notes**

**Documentation Changes**

### CODE REVIEW

**Comment by josecordaz** [comment]
@rokshana-b @iahmad9 Any reason why we have this duplicate register (`RegisterFailHandler `)  ?

**Comment by palemtnrider** [comment]
Do you have some example output before/after this change? The change LGTM but seeing the output would help.

Also, you may have been able to provide a skip in the call to ginko.Fail()

**Comment by josecordaz** [comment]
> Do you have some example output before/after this change? The change LGTM but seeing the output would help.

You right, an example of the output would be really helpful. The actual difference is in the description of the ticket. https://github.com/weaveworks/weave-gitops/issues/1164
> 
> Also, you may have been able to provide a skip in the call to ginko.Fail()

You mean, like a parameter?

**Review by rokshana-b — APPROVED** [review]

**Comment by palemtnrider** [comment]
> You mean, like a parameter?

Yes.  There is a callerSkip argument that should change who is reporting the error.

**Review by palemtnrider — APPROVED** [review]
LGTM

**Pull request merged**
