### PR TITLE
UI - update tabs view

### LINKED ISSUE #3918: Tab View Enhancement
### The Problem
Tabs are not visually related to the content beneath them, as shown in the screenshot below:
image

This inconsistency is observed across the system and on various pages.

### Proposed Solution
A small enhancement that adds an underline will effortlessly address this issue and create a better visual connection between the tabs and their corresponding content.
as shown in the screenshot below:
image

 Please feel free to share your thoughts so we can further improve the user experience. Thank you!

### PR DESCRIPTION
**Pull request by AsmaaNabilBakr**
Closes #3918 

**What changed?**
 - update tabs view style to be consistent with the [design](https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?type=design&node-id=19136-224722&mode=design&t=5SvZj3bO4Gvlj8Ax-0)
 
 Before: 
image

image

After: 
image

image

### CODE REVIEW

**Review by jpellizzari — APPROVED** [review]

**Review by joshri — CHANGES_REQUESTED** [review]
It looks like there wasn't a design for this in Dark Mode, but imo the double underline doesn't look quite right @mmoulian @alfaris I want to make sure this is design approved
image

There's an unused import of Spacer in `SubRouterTabs` that needs to be deleted for CI to pass

**Comment by alfaris** [comment]
@joshri the double line in new tabs is approved
you could check this issue #3918

**Review by joshri — DISMISSED** [review]
@alfaris I looked at the issue as well as the figma doc before reviewing, and there is no reference to what the colors should be in dark mode. Please add so we can reference in reviews in the future. Glad to hear it's approved

**Comment by mmoulian** [comment]
@alfaris  and @joshri The double line in Dark mode is also strange to me. I think that we can review it

**Comment by TheGostKasper** [comment]
@mmoulian @joshri any concerns to merge !?

**Comment by joshri** [comment]
> @mmoulian @joshri any concerns to merge !?

Yes we are waiting on a design update on this

**Comment by mmoulian** [comment]
I think that this option has more votes:

Design link: https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?type=design&node-id=19761%3A1314&mode=design&t=OpngzkBWT6aapjtm-1

Tab-2

**Comment by TheGostKasper** [comment]
@mmoulian just to make sure that tab container will have a border bottom and each tab item will also has a border line of maybe `2px` , Doesn't it feels weird ?

image

**Comment by alfaris** [comment]
> @alfaris @mmoulian just to make sure that tab container will have a border bottom and each tab item will also has a border line of maybe `2px` , Doesn't it feels weird ?
> 
> image

We can make every tab have 1px gray bottom line and only the active one have it 2px colored with our primary color whether it's light or dark mode

**Comment by AsmaaNabilBakr** [comment]
@alfaris @mmoulian @joshri  I updated the PR with the new screenshots, kindly confirm.

**Review by joshri — APPROVED** [review]

**Pull request merged**
