### PR TITLE
Re-work table filtering to match designs

### LINKED ISSUE #1618: Invert filtering logic for FilterableTable
When the user clicks on "Kustomization", only kustomizations show up, and therefore adds a chip

### PR DESCRIPTION
**Pull request by jpellizzari**
Closes #1618

Video: https://drive.google.com/file/d/1TGyD9E2F8DnLN_dGlDn1070M5be8iXN_/view?usp=sharing

### CODE REVIEW

**Review by sympatheticmoose — APPROVED** [review]
LGTM - approved based on video

**Comment by sympatheticmoose** [comment]
> LGTM - approved based on video

Also @jpellizzari thank you for the video to help with reviewing ⭐

**Review by joshri — APPROVED** [review]
⭐  A P P R O V E D ⭐

**Comment by bia** [comment]
Nice work! And thank you for posting the video @jpellizzari .

I've created follow up issue #1708 for further styling refinements.

**Pull request merged**
