### PR TITLE
Disable checkpoint for all CI jobs

### PR DESCRIPTION
**Pull request by rokshana-b**
**What changed?**
Added `CHECKPOINT_DISABLE` env on all test jobs

**Why?**
To avoid interfering with the statistics that keep track of the number of downloads customers are making for `Weave-GitOps`

### CODE REVIEW

**Review by palemtnrider — CHANGES_REQUESTED** [review]
NIT I think the code is easier to read if you add this override in the `env:`.  The coverage tests in the deploy action is missing the override.

**Comment by rokshana-b** [comment]
> NIT I think the code is easier to read if you add this override in the `env:`. The coverage tests in the deploy action is missing the override.

So just adding the `CHECKPOINT_DISABLE` in the list of other envs should work, right? I'll do that then

**Comment by rokshana-b** [comment]
@palemtnrider is there a way to test if the changes in this PR have the desired effect?

**Review by iahmad9 — APPROVED** [review]
LGTM

**Pull request merged**
