### PR TITLE
Modify the local build to install and configure tilt for first runners

### PR DESCRIPTION
**Pull request by Skarlso**
Tilt install assume you already have a working cluster. That's not really needed.

Now that we have acceptance test change how we handle the image in the real deployment yaml file, we can bootstrap a dev environment and then let tilt take over so it monitors all files.

Screenshot 2022-02-08 at 12 53 25

This is now working with a booted up dev cluster from 0 -> 100 without running anything before hand just this:

```
TEST_CONFIG_REPO=ssh://git@github.com/Skarlso/gitops-training.git make cluster-dev
```

There is also a convenient make target to clean everything up: `make clean-dev-cluster`.

# Question

Do people would like to have an option to disable the bootstrap part and still use tilt with an existing cluster?

Closes https://github.com/weaveworks/weave-gitops/issues/1406

### CODE REVIEW

**Comment by nikimanoledaki** [comment]
awesome, trying it out now! could you also update/add instructions to the contributing guide please? :))

**Review by jpellizzari — APPROVED** [review]
👍 Nice work

**Review by nikimanoledaki — APPROVED** [review]

**Comment by jpellizzari** [comment]
@Skarlso Don't we also have to set the ports to `5001` in the `./tools/kind-with-registry` script?

**Comment by Skarlso** [comment]
You appear to have an old kind registry. Please delete it and try again?

**Pull request merged**
