### PR TITLE
new issue template - feature request

### PR DESCRIPTION
**Pull request by sympatheticmoose**
Proposes new issue template for community members to share their ideas on improving the project.

### CODE REVIEW

**Review by makkes — APPROVED** [review]
LGTM. IMHO we should also just remove the "Spike" template.

**Comment by sympatheticmoose** [comment]
@makkes - why?

**Comment by makkes** [comment]
> @makkes - why?

It feels unintuitive to someone new to the project. Other projects have more descriptive templates:

Flux: 

Kubernetes: 

Argo: 

How would someone know what a spike means? Or a story for that matter.

**Comment by sympatheticmoose** [comment]
> It feels unintuitive to someone new to the project

agree.

> [...] Or a story for that matter

similarly agree.

---

However, we're only at a total of 4 templates, which isn't that hard to scan to find the closest fit, which for most will be bug report or feature request (now).

If the other templates provide value to the weaveworks engineering teams regularly contributing to the project, I think that's ok for now.

**Pull request merged**
