### PR TITLE
fix: Return UserInfo{} if superuser not logged in

### LINKED ISSUE #1658: UserInfo panic'ing
Seems to happen after a dev rebuild in Tilt; not sure on exact repro steps:

```
2022/03/09 23:36:25 http: panic serving 127.0.0.1:33762: runtime error: invalid memory address or nil pointer dereference
goroutine 455 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1802 +0x13a
panic({0x2ab3860, 0x4f83160})
	/usr/local/go/src/runtime/panic.go:1047 +0x262
github.com/coreos/go-oidc/v3/oidc.(*Provider).UserInfo(0x0, {0x3eb4b20, 0xc000af3840}, {0x3e7ccc0, 0xc000cb3680})
	/home/jordan/go/pkg/mod/github.com/coreos/go-oidc/v3@v3.1.0/oidc/oidc.go:247 +0x6e
github.com/weaveworks/weave-gitops/pkg/server/auth.(*AuthServer).UserInfo.func1({0x3eaae20, 0xc000f580e0}, 0xc00055ce00)
	/home/jordan/Projects/weave-gitops/pkg/server/auth/server.go:326 +0x3a5
net/http.HandlerFunc.ServeHTTP(0xc000d88760, {0x3eaae20, 0xc000f580e0}, 0xc00055ce00)
	/usr/local/go/src/net/http/server.go:2047 +0x43
net/http.(*ServeMux).ServeHTTP(0xc000722b40, {0x3eaae20, 0xc000f580e0}, 0xc00055ce00)
	/usr/local/go/src/net/http/server.go:2425 +0x135
net/http.serverHandler.ServeHTTP({0xc00026c7e0}, {0x3eaae20, 0xc000f580e0}, 0xc00055ce00)
	/usr/local/go/src/net/http/server.go:2879 +0x47a
net/http.(*conn).serve(0xc000f22820, {0x3eb4b20, 0xc000af37c0})
	/usr/local/go/src/net/http/server.go:1930 +0x18b8
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3034 +0xa38
2022/03/09 23:36:26 http: panic serving 127.0.0.1:33780: runtime error: invalid memory address or nil pointer dereference
goroutine 457 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1802 +0x13a
panic({0x2ab3860, 0x4f83160})
	/usr/local/go/src/runtime/panic.go:1047 +0x262
github.com/coreos/go-oidc/v3/oidc.(*Provider).UserInfo(0x0, {0x3eb4b20, 0xc000af3900}, {0x3e7ccc0, 0xc000cb37a0})
	/home/jordan/go/pkg/mod/github.com/coreos/go-oidc/v3@v3.1.0/oidc/oidc.go:247 +0x6e
github.com/weaveworks/weave-gitops/pkg/server/auth.(*AuthServer).UserInfo.func1({0x3eaae20, 0xc000f581c0}, 0xc00055d100)
	/home/jordan/Projects/weave-gitops/pkg/server/auth/server.go:326 +0x3a5
net/http.HandlerFunc.ServeHTTP(0xc000d88760, {0x3eaae20, 0xc000f581c0}, 0xc00055d100)
	/usr/local/go/src/net/http/server.go:2047 +0x43
net/http.(*ServeMux).ServeHTTP(0xc000722b40, {0x3eaae20, 0xc000f581c0}, 0xc00055d100)
	/usr/local/go/src/net/http/server.go:2425 +0x135
net/http.serverHandler.ServeHTTP({0xc00026c7e0}, {0x3eaae20, 0xc000f581c0}, 0xc00055d100)
	/usr/local/go/src/net/http/server.go:2879 +0x47a
net/http.(*conn).serve(0xc000f228c0, {0x3eb4b20, 0xc000af3880})
	/usr/local/go/src/net/http/server.go:1930 +0x18b8
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3034 +0xa38
```

### PR DESCRIPTION
**Pull request by Callisto13**
We want to leave early in the case that OIDC is not enabled and thus the
provider is not set.

Closes #1658 see last comment for context.

### CODE REVIEW

**Comment by Callisto13** [comment]
We have very few tests (read: 2) around auth, but I am conscious that the other team are adding more stuff to this all the time. I want to be a good citizen and add coverage for the superuser flow, but appreciate this may make the merge even harder.

WDYT @jpellizzari

**Comment by jpellizzari** [comment]
@Callisto13  We do have #1564 for UI stuff, but yes we may be a tad lacking on tests for BE stuff.

Maybe a quick ping to @yiannistri and @AlinaGoaga regarding what they are working on?

We can even be clever about naming a file with tests so as to avoid merge conflicts.

I would say that tests for the superuser flow are valuable enough to warrant some possible merge-pain @Callisto13 .

**Comment by Callisto13** [comment]
There were tests, just not on my branch 😆 . I changed the base to `main` now that we are working there again and tidied up the existing tests, adding one of my own which reproed the failure nicely.

**Review by yitsushi — APPROVED** [review]

**Comment by Callisto13** [comment]
huh, how do i get that check to actually run?

**Comment by Callisto13** [comment]
I think I am going to have to close and reopen this

**Pull request closed without merging**
