### PR TITLE
Update auth check

### PR DESCRIPTION
**Pull request by AlinaGoaga**
Switch to checking user info instead of loading to stop flickering when navigating

### CODE REVIEW

**Comment by jpellizzari** [comment]
Maybe Closes https://github.com/weaveworks/weave-gitops/issues/1900

**Comment by AlinaGoaga** [comment]
Indeed, thanks @jpellizzari! :)

**Comment by foot** [comment]
> Maybe Closes https://github.com/weaveworks/weave-gitops/issues/1900

I think so. We could refactor the whole AuthCheck thing to useQuery too where `isLoading` behaves a bit more in-align w/ what we're after. This is a bit of a quick-fix so we can get a release out the door. 😬

**Review by foot — APPROVED** [review]
💯 

There is still a small jank on the first load, I think as the feature flags come in and force a re-render. That will hopefully be fixed in #1983.

Still, feels much better!

**Comment by AlinaGoaga** [comment]
Yup, I've got that on the list - make more use of `useQuery` (was going to work on it as part of the refactoring on [https://github.com/weaveworks/weave-gitops/pull/1983](url)) ;)

**Pull request merged**
