### PR TITLE
Update deploy.mdx

### PR DESCRIPTION
**Pull request by jear**
Closes

**What changed?**

**Why was this change made?**

**How was this change implemented?**

**How did you validate the change?**

**Release notes**

**Documentation Changes**

### CODE REVIEW

**Comment by jear** [comment]
flux delete kustomization -n flux-system podinfo
Are you sure you want to delete this kustomization: y
► deleting kustomization podinfo in flux-system namespace
✔ kustomization deleted

 flux delete  source git  podinfo
Are you sure you want to delete this source git: y
► deleting source git podinfo in flux-system namespace
✔ source git deleted

**Comment by jear** [comment]
not enough, podinfo is coming back :-)

**Comment by yiannistri** [comment]
@LappleApple I think this PR is meant to update the docs to show how to remove the podinfo deployment, upon completion of the getting started guide. Let me know how you want to proceed on this one.

**Comment by LappleApple** [comment]
@jear Thank you for pointing out this issue and helping us to make WeGO docs better.

**Pull request closed without merging**
