### PR TITLE
Enable code scanning upload on failure

### PR DESCRIPTION
**Pull request by palemtnrider**
Closes: 

**What changed?**
Updating the snyk action to upload results even on failure.  

**Why?**
The only output is the log from the action.  Having it available in the security tab will be useful. This upload enables us to triage the problem and either fix it or mark as a false positive.

**How did you test it?**
Ran the action

### CODE REVIEW

**Review by jpellizzari — APPROVED** [review]
Green :heavy_check_mark: looks good to me! I wish we could get rid of these license warnings, but I suspect that is a different issue.

**Comment by mnowster** [comment]
Why are we uploading to the tab and not back to snyk itself as per https://github.com/weaveworks/weave-gitops/pull/1294

Doesn't this give a false positive of hey snyk says green?

**Comment by palemtnrider** [comment]
> Why are we uploading to the tab and not back to snyk itself as per #1294
> 
> Doesn't this give a false positive of hey snyk says green?

@mnowster Sort of.  The job doesn't fail, but the files tab shows the failed checks giving us the ability to review them here.

**Comment by palemtnrider** [comment]
@mnowster a bit more details. that test created a duplicate weaveworks/weave-gitops project.  I was able to go into snyk and update those checks.

**Review by mnowster — CHANGES_REQUESTED** [review]
🙅🏻‍♀️  I don't agree with this approach. 

I would rather we change the licence severity in the config in snyk, so that it correctly shows fail mark on a PR if something is introduced. 
I think that this would be better if it uses the monitor command so it reports the data back to snyk, so it's able to be emailed to a group of people and reported on.

**Comment by palemtnrider** [comment]
Closing.  The code will fail if new dependencies don't pass the snyk scan.  However, we will still upload the scan results on a successful run - i.e. this PR doesn't address that existing behavior.  That should be addressed in a new PR - (similar #1294 )

**Pull request closed without merging**
