### PR TITLE
Update frontend dev process docs

### LINKED ISSUE #3607: Update documentation for frontend development with HMR
The command listed in the the development-process.mdx document is different from the actual commands used by frontend developers:

In the first terminal:
```
FAST_AND_FURIOUSER=1 SKIP_UI_BUILD=1 tilt up
```
In the second terminal:

```
npm install && npm start
```

In addition, I also had to run `npm run build` before `npm install && npm start` to make the command work for me. Otherwise the runtime was yellow in Tilt.

### PR DESCRIPTION
**Pull request by joshri**
Closes #3607 

Docs were outdated in terms of the bash variables needed - added `FAST_AND_FURIOUSER` as well as `SKIP_UI_BUILD`.

### CODE REVIEW

**Comment by joshri** [comment]
@jpellizzari does the dev-process doc seem right to you?

**Comment by jpellizzari** [comment]
@joshri Not sure what `MANUAL_MODE` is?

**Review by jpellizzari — APPROVED** [review]
@joshri Not sure what MANUAL_MODE is?

Improves the docs so 👍

**Comment by joshri** [comment]
> @joshri Not sure what MANUAL_MODE is?
> 
> Improves the docs so 👍
The MANUAL_MODE thing was already there, so I left it in, but I don't have it on myself.

From the tiltfile:
`if os.getenv('MANUAL_MODE'):
   trigger_mode(TRIGGER_MODE_MANUAL)`

this is the page in the tilt docs for this https://docs.tilt.dev/manual_update_control.html

Seems like it makes you refresh your tilt resources yourself. Maybe it's the secret ingredient I've been missing.

**Comment by jpellizzari** [comment]
> Seems like it makes you refresh your tilt resources yourself

If that is the case, it should not be the default. I would say if you are doing FE dev regularly `FASTER_AND_FURIOUSER` and `SKIP_UI_BUILD` should be turned on, since you will be using the dev server.

**Comment by joshri** [comment]
> > Seems like it makes you refresh your tilt resources yourself
> 
> If that is the case, it should not be the default. I would say if you are doing FE dev regularly `FASTER_AND_FURIOUSER` and `SKIP_UI_BUILD` should be turned on, since you will be using the dev server.

Coolio I'll remove it

**Pull request merged**
