### PR TITLE
Add new background plus header changes to match

### LINKED ISSUE #2377: Change background image and remove blue header background
New [background image](https://drive.google.com/open?id=12uiUhIvQfffiWn3YfCqZZVm3qFj2YY3f&authuser=bianca%40weave.works&usp=drive_fs), new look : 
20220712new-bg

### Acceptance Criteria

1. This does not change the existing scrolling behavior within the application.  I would still expect the content to scroll under the header as well as the left/right scrolling to remain independent of each other.
2. Header text is `20px` Proxima Nova 'Neutral 30' (`#1a1a1a`) in `bold` and `regular` with `16px` padding separating the titles with a number count (`2px` roundrect in 'Primary -10' `#98E0F7`) and a right-facing [chevron icon](https://fonts.google.com/icons?selected=Material%20Icons%3Achevron_right%3A).

Note: we might need to modify the opacity in the app across the board depending on how the new background works.

Note: this is a screenshot of the enterprise version so (total count in bread crumb) and extra menu items will not exist.

### References

[Figma](https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?node-id=9469%3A50766)
[background image](https://drive.google.com/open?id=12uiUhIvQfffiWn3YfCqZZVm3qFj2YY3f&authuser=bianca%40weave.works&usp=drive_fs)

### LINKED ISSUE #2380: Change user icon to 'Person'
instead of 'Account Circle' to match current designs.
Inactive color is `Neutral 30` `#737373`

Material icon file is here : https://fonts.google.com/icons?selected=Material%20Icons%3Aperson%3A

20220621WIP Release Detail View - SIDE BAR 02 Icons

### Acceptance Critiera

1 header -User enabled
2 header-User hover
3 Header-user active

https://user-images.githubusercontent.com/95616291/182905531-d782d48d-74da-4c65-8116-d99476e22954.mov

### PR DESCRIPTION
**Pull request by joshri**
Closes #2377 
Closes #2380

- new background
- header background color
- major icon changes for user settings in header
- fixes spacing bug where empty errors and main content were spaced with justify-content: space-between leading to extra white space before main content

https://user-images.githubusercontent.com/65822698/183713809-a6fa9809-4b31-40bd-b000-5f92c19a8e41.mov

### CODE REVIEW

**Comment by opudrovs** [comment]
This is what I see for this branch when running the app via `tilt up`:

Screenshot 2022-08-09 at 19 43 12

- Is the table is looking different from what is expected?

- And shouldn't the icon circle on the screenshots and in Figma (I think, hope I looked in the right place) blend completely with the background?

**Comment by joshri** [comment]
This is me on localhost:9001 from tilt:
image

It was grey like your screenshot for a second - then I went into the chrome dev tools responsiveness thing to check out if I could make the gap in the chip component show up, and when I went back, it looked like my screenshot. I even included the url to make sure I was on 9001 from tilt cause I'm so confused. Looks like we need to start using gitops run. Maybe we can get Robin's help getting things consistent between us?

**Comment by opudrovs** [comment]
@joshri so, the screenshot you posted now is what you saw initially, it disappeared fast?

Let me retest your branch again in a clean repo, with cached files removed and with a default version of Flux.

**Comment by joshri** [comment]
I saw your version (without the white space where the chips are) for a second then it changed. Sorry to make you reset everything :(

**Comment by opudrovs** [comment]
It's OK, we need to find out what is wrong.

Here is what I see after cleaning everything:

Screenshot 2022-08-09 at 20 44 02

Screenshot 2022-08-09 at 20 46 14

I noticed that my versions of K8s and Flux are newer than yours. What else can be different?

**Comment by opudrovs** [comment]
My versions:

Screenshot 2022-08-09 at 20 51 06

**Comment by opudrovs** [comment]
@joshri is the table on your machine white and does the icon BG blend with the header background as expected?

**Comment by joshri** [comment]
The header background is supposed to blend with the icon bg standing out like I have - that header background that you have is a different color than main but not the correct one which is.....weird. Could be a previous commit somehow? I will update k8s and flux and see what happens

**Comment by opudrovs** [comment]
@joshri Interesting, I checked out the `2377-background` branch into a clean repo.

is the latest version of your changes committed? Were there any issues with rebase? Some weeks ago I had an issue when a quirky rebase was replacing my latest changes with earlier commits for some reason. Had to create a different branch for that PR.

**Comment by joshri** [comment]
UPDATE: image resizing at certain screen widths breaks the nice blending between the header and bg seen here:

https://user-images.githubusercontent.com/65822698/183921924-8a5255c9-0b5d-4268-a66e-3f4b04ae844c.mov

As discussed with design, we will be separating the cool circles from the gradient to allow the circles to scale while keeping the header/bg blend

**Comment by opudrovs** [comment]
@joshri here is what I see with tilt:

Screenshot 2022-08-11 at 17 55 07

**Comment by opudrovs** [comment]
Looks the same to me, great job! If that's all, I'm approving the PR.

**Comment by opudrovs** [comment]
@joshri the only thing I didn't get is why the first menu item, `Hello, dev`, can be clicked. What does it do?

**Comment by joshri** [comment]
> @joshri the only thing I didn't get is why the first menu item, `Hello, dev`, is clickable. What does it do?

I have no idea............maybe enterprise has it actually link to something? More than likely it's useless.

**Comment by opudrovs** [comment]
@joshri thanks for the info. 😺

**Pull request merged**
