### PR TITLE
Style Icon Button Hover State

### PR DESCRIPTION
**Pull request by joshri**
Related to #1853 

`IconButton` styled component can be exported for cases where the only button content is an icon, in which case we want the hover state to be a circle. 

Pictured - glorious circle hover state
image

### CODE REVIEW

**Comment by jpellizzari** [comment]
@joshri I see other margin changes happening here. Screenshots?

**Comment by joshri** [comment]
@jpellizzari The margin changes are all concerning the chip group - previous version caused some alignment issues. You can also see the active hover state with the circle here

image

**Comment by jpellizzari** [comment]
As long as it looks okay without any `Chips` :+1:

**Review by jpellizzari — APPROVED** [review]

**Comment by joshri** [comment]
> As long as it looks okay without any `Chips` 👍

No chips screenshot just for the record 
image

**Pull request merged**
