### PR TITLE
Add values for OIDC settings to chart.

### LINKED ISSUE #3833: gitops-server helm chart: Missing fields for oidc auth secret
**Describe the bug**

The documentation for oidc describes the ability to define the following fields for the secret:

https://docs.gitops.weave.works/docs/configuration/oidc-access/#scopes

```
  --from-literal=tokenDuration=<token-duration> \
  --from-literal=customScopes=custom,scopes
```

https://docs.gitops.weave.works/docs/configuration/oidc-access/#claims

```
  --from-literal=claimUsername=sub \
  --from-literal=claimGroups=groups
```

The gitops-server helm chart secret does not provide the ability to set these fields in the oidc-auth-secret.yaml and they are not referenced in the values.yaml

https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/templates/oidc-auth-secret.yaml

```
# https://docs.gitops.weave.works/docs/configuration/securing-access-to-the-dashboard/#login-via-an-oidc-provider
oidcSecret:
  create: false
  # clientID:
  # clientSecret:
  # issuerURL:
  # redirectURL:
```
  
**Environment**

- Weave-Gitops Version: v0.27.0
- Flux Version: 2.0.0
- Kubernetes version: 1.26

**Expected behavior**

This is a request to enhance the chart to include these fields

### PR DESCRIPTION
**Pull request by bigkevmcd**
Closes #3833

**What changed?**
This rounds out support for the additional OIDC fields to the oidc-auth secret.

New values.yaml fields are added, and the secret is generated with the new fields when populated.

**Why was this change made?**
To fix the issue that this Closes.

**How was this change implemented?**
New values.yaml fields are added, and the secret is generated with the new fields when populated.

**How did you validate the change?**
Applied the chart with a configured values yaml and verified that the secret contains the fields in base64 format.

**Release notes**
Configure optional OIDC fields in the auth secret.

**Documentation Changes**

### CODE REVIEW

**Comment by dmcanally-leolabs** [comment]
Can this PR get re-opened and merged?

**Comment by dmcanally-leolabs** [comment]
@bigkevmcd, is there any particular reason why you closed this PR? I'm curious because the workaround for this is exposes secret values in the deployment manifest.

**Comment by bigkevmcd** [comment]
@dmcanally-leolabs Honest answer, lack of time, it wasn't getting reviewed, and I only have a limited amount of bandwidth.

**Comment by bigkevmcd** [comment]
Also, there was nothing preventing someone creating the secret, and if I'm honest, I'm not a fan of increasing the support load of Helm charts (everything we add, we need to support)

**Comment by dmcanally-leolabs** [comment]
I understand. Thanks for replying so quickly.

**Pull request closed without merging**
